### ISSUE TITLE
Just the first value of the observation parameters is being stored

### ISSUE THREAD

**Issue by ridoo** [52North/sensorweb-server-sta#87]
The STA takes only the first observation parameter. In the database also just one parameter is stored. For example

```
{
    "phenomenonTime": "2012-06-26T03:42:02-06:00",
    "result": 70.4,
    "parameters": [{
	    "name": "foo",
	    "value": "bar"
    },{
	    "name": "bar",
	    "value": "baz"
    }]
}
```

will result in

```
{
    "@iot.count": 1,
    "value": [
        {
            "@iot.id": "79d9517f-06f5-4465-9383-22026b40df90",
            "@iot.selfLink": "http://localhost:8080/sta/Observations(79d9517f-06f5-4465-9383-22026b40df90)",
            "result": "70.4000000000",
            "resultTime": null,
            "phenomenonTime": "2012-06-26T09:42:02.000Z",
            "resultQuality": null,
            "validTime": null,
            "parameters": [
                {
                    "name": "foo",
                    "value": "bar"
                }
            ],
            "Datastream@iot.navigationLink": "http://localhost:8080/sta/Observations(79d9517f-06f5-4465-9383-22026b40df90)/Datastream",
            "FeatureOfInterest@iot.navigationLink": "http://localhost:8080/sta/Observations(79d9517f-06f5-4465-9383-22026b40df90)/FeatureOfInterest"
        }
    ]
}
```

**Comment by SpeckiJ** [comment]
This is caused by a wrong equality/duplicate hashCode when adding the parameters to the HashSet used while deserializing from JSON here: https://github.com/52North/sensorweb-server-sta/blob/e196f07c69ec6b0c2815db9b0d9d9cff25d9cbf7/core/src/main/java/org/n52/sta/serdes/json/JSONObservation.java#L236

The `ParameterEntity->equals` and `ParameterEntity->hashCode` is inherited from `IdEntity` and solely based on the Id, which is not set as it is generated by the database during peristing.

I have fixed the issue in https://github.com/52North/sensorweb-server-db-model/commit/39f3418be0c7151bc77be571cc981866e2e99379
